In [1]:
import numpy as np


<h>-------------------- Manipulating The Array -----------------------</h>

<h> 1. Flattening </h>

<p> Flattening an array means converting a multi-dimensional array into a one-dimensional array.

In [14]:
arr1=np.array([[1,2,3],[2,4,6],[4,6,8]])
arr2=np.array([[[1,2,3],[2,4,6]],[[7,9,10],[4,3,6]]])
print(arr1)
print("-"*10)
print(*arr2)

print("-"*10)
# Now Flatening 
flatten_array=arr1.flatten()
print(flatten_array)
print("-"*10)
flatten2_arr2=arr2.flatten()
print(flatten2_arr2)

[[1 2 3]
 [2 4 6]
 [4 6 8]]
----------
[[1 2 3]
 [2 4 6]] [[ 7  9 10]
 [ 4  3  6]]
----------
[1 2 3 2 4 6 4 6 8]
----------
[ 1  2  3  2  4  6  7  9 10  4  3  6]


<h> 2. Reshaping </h>
<p> Reshaping an array involves changing the shape of the array while preserving its elements.
Example illustrates reshaping a 2D array into a different shape using the 'reshape' method.

In [31]:
arr1=np.array([[1,2,3],[2,4,6]])
print(arr1.shape)
arr2=np.array([[[1,2,3],[2,4,6]],[[7,9,10],[4,3,6]]])
reshape_arry=np.reshape(arr1,(3,2))
print(reshape_arry)

print('-'*10)
print(arr2.shape)
reshapearr2_array=np.reshape(arr2,(3,2,2)) # without changing its data 

print(reshapearr2_array)

(2, 3)
[[1 2]
 [3 2]
 [4 6]]
----------
(2, 2, 3)
[[[ 1  2]
  [ 3  2]]

 [[ 4  6]
  [ 7  9]]

 [[10  4]
  [ 3  6]]]


<h> 3. Splitting </h>

<p> Splitting arrays allows dividing an array into multiple sub-arrays along a specified axis.

Examples demonstrate vertical and horizontal splitting using 'vsplit' and 'hsplit', as well as generic splitting using 'split'.

* Vsplit --> Vertical Split 

In [43]:
arr2=np.array(((1,2,3),(2,4,6),(12,24,36),(23,34,56)))
print(arr2)
Vsplit_arry=np.vsplit(arr2,4)
print(Vsplit_arry)

[[ 1  2  3]
 [ 2  4  6]
 [12 24 36]
 [23 34 56]]
[array([[1, 2, 3]]), array([[2, 4, 6]]), array([[12, 24, 36]]), array([[23, 34, 56]])]


In [44]:
Vsplit_arry=np.vsplit(arr2,2)
print(Vsplit_arry)

[array([[1, 2, 3],
       [2, 4, 6]]), array([[12, 24, 36],
       [23, 34, 56]])]


<h> Cannot divide the aray in three equal parts interpreter will throw an error 


In [45]:
Vsplit_arry=np.vsplit(arr2,3)
print(Vsplit_arry)

ValueError: array split does not result in an equal division

<h> * hsplit --> horizontal split 

In [58]:
arr2=np.array(((1,2,3),(2,4,6),(12,24,36),(23,34,56)))
print(arr2.shape)
print(arr2)
hspli_arry=np.hsplit(arr2,3)
print(hspli_arry)

(4, 3)
[[ 1  2  3]
 [ 2  4  6]
 [12 24 36]
 [23 34 56]]
[array([[ 1],
       [ 2],
       [12],
       [23]]), array([[ 2],
       [ 4],
       [24],
       [34]]), array([[ 3],
       [ 6],
       [36],
       [56]])]


In [ ]:
arr2=np.array(((1,2,3),(2,4,6),(12,24,36),(23,34,56)))
print(arr2.shape)
print(arr2)
hspli_arry=np.hsplit(arr2,3)
print(hspli_arry)

<h> 4. Merging </h>

<p> Merging involves combining multiple arrays into a single array.
Examples showcase concatenating arrays along different axes using 'concatenate', 'hstack', 'vstack', and 'stack'.

<h> * concerdinate

In [65]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3=np.array([12,24,36,48,60])
concer_ary=np.concatenate((arr1,arr2))
print(concer_ary)

[1 2 3 4 1 5 2 9]


In [67]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3=np.array([12,24,36,48,60])
concer_ary=np.concatenate((arr1,arr2,arr3))
print(concer_ary)

[ 1  2  3  4  1  5  2  9 12 24 36 48 60]


<h> * vstack 

In [77]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([1,2,6,8])
arr4 = np.array([2,4,3,8,])
vstack_array=np.vstack((arr1,arr2,arr3,arr4))
print(vstack_array)

[[1 2 3 4]
 [1 5 2 9]
 [1 2 6 8]
 [2 4 3 8]]


In [74]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.vstack((arr1,arr2,arr3,arr4))

print(concat_arr)

[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]


In [78]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

concat_arr = np.hstack((arr1,arr2,arr3,arr4))

print(concat_arr)

[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]


In [79]:
i=0
while i<3:
    print(i)
    i=i+1
else:
    print("done ")

0
1
2
done 


In [80]:
s="data science"
print(s[5:])

science
