### ** --------- Broadcasting for efficient calculation in numpy array ------------

##### NumPy's broadcasting feature allows for efficient element-wise operations between arrays of different shapes without the need for explicit looping. In this article, we'll explore how broadcasting works and how it can be leveraged for arithmetic, comparison, logical, and bitwise operations in NumPy.

#### 1. arithmetic operatins 


In [8]:
## addition 
import numpy as np 
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)

print("--"*10)

print(arr1+arr2)
print(arr1+2)
print(arr2+2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[ 2  4  6  8]
 [ 6  8 10 12]]
[3 4 5 6]
[[ 3  4  5  6]
 [ 7  8  9 10]]


In [12]:
## 2 dimensional array
arr1=np.array([[1,2,3,4],[10,11,20,30]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)
print("--"*10)
print(arr1+arr2)

[[ 1  2  3  4]
 [10 11 20 30]]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[ 2  4  6  8]
 [15 17 27 38]]


In [16]:
## 3 dimensional arrray
arr3=np.array([[[2,4,6,8],[1,2,3,4]],[[5,6,7,8],[3,5,7,9]]])
arr4=np.array([[3,6,9,12],[12,24,36,48],[2,4,6,8],[1,3,5,7]])

print(arr3+arr4)


ValueError: operands could not be broadcast together with shapes (2,2,4) (4,4) 

In [17]:
arr3=np.array([[[2,4,6,8],[1,2,3,4]],[[5,6,7,8],[3,5,7,9]]])
arr4=np.array([[[3,6,9,12],[12,24,36,48]],[[2,4,6,8],[1,3,5,7]]])

print(arr3)
print("-"*10)
print(arr4)

print("-"*10)

print(arr3+arr4)

[[[2 4 6 8]
  [1 2 3 4]]

 [[5 6 7 8]
  [3 5 7 9]]]
----------
[[[ 3  6  9 12]
  [12 24 36 48]]

 [[ 2  4  6  8]
  [ 1  3  5  7]]]
----------
[[[ 5 10 15 20]
  [13 26 39 52]]

 [[ 7 10 13 16]
  [ 4  8 12 16]]]


In [18]:
## subtraction 
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)

print("--"*10)

print(arr1-arr2)
print(arr1-2)
print(arr2-2)



[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[ 0  0  0  0]
 [-4 -4 -4 -4]]
[-1  0  1  2]
[[-1  0  1  2]
 [ 3  4  5  6]]


In [19]:
## multiplication 
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)

print("--"*10)

print(arr1*arr2)
print(arr1*2)
print(arr2*2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[ 1  4  9 16]
 [ 5 12 21 32]]
[2 4 6 8]
[[ 2  4  6  8]
 [10 12 14 16]]


In [20]:
### Divide 
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)

print("--"*10)

print(arr1/arr2)
print(arr1/2)
print(arr2/2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[1.         1.         1.         1.        ]
 [0.2        0.33333333 0.42857143 0.5       ]]
[0.5 1.  1.5 2. ]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]]


In [21]:
# Exponential 
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)

print("--"*10)

print(arr1**arr2)
print(arr1**2)
print(arr2**2)


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[    1     4    27   256]
 [    1    64  2187 65536]]
[ 1  4  9 16]
[[ 1  4  9 16]
 [25 36 49 64]]


In [22]:
## Modulo 
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)

print("--"*10)

print(arr1%arr2)
print(arr1%2)
print(arr2%2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[0 0 0 0]
 [1 2 3 4]]
[1 0 1 0]
[[1 0 1 0]
 [1 0 1 0]]


#### 2. comparison 

In [24]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print(arr2)

print("--"*10)

# >(greater than)
print(arr1>arr2)
print(arr2>arr1)



[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[False False False False]
 [False False False False]]
[[False False False False]
 [ True  True  True  True]]


In [25]:
# <(less than)
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])

print("--"*10)

print(arr1<arr2)
print("--"*10)
print(arr2<arr1)

--------------------
[[False False False False]
 [ True  True  True  True]]
--------------------
[[False False False False]
 [False False False False]]


In [27]:
# >= 

arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])

print("--"*10)

print(arr1>=arr2)
print("--"*10)
print(arr2>=arr1)

--------------------
[[ True  True  True  True]
 [False False False False]]
--------------------
[[ True  True  True  True]
 [ True  True  True  True]]


In [29]:
## <=
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])

print("--"*10)

print(arr1<=arr2)
print("--"*10)
print(arr2<=arr1)

--------------------
[[ True  True  True  True]
 [ True  True  True  True]]
--------------------
[[ True  True  True  True]
 [False False False False]]


#### 3. Logical 

In [30]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])
print(a)
print(b)

print('-'*10)

print(a & b)
print('-'*10)

print(a | b)
print('-'*10)

print(a ^ b)
print('-'*10)


[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[1 2 3]
 [0 0 2]]
----------
[[1 2 3]
 [5 7 7]]
----------
[[0 0 0]
 [5 7 5]]
----------


#### 4. Bitwise 

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

print(np.bitwise_and(a,b))

print(np.bitwise_or(a,b))

print(np.bitwise_xor(a,b))

print(np.bitwise_not(a,b))

print(np.right_shift(a,b))

print(np.left_shift(a,b))
