<h>------------------ Essebtial functions in numpy --------------------</h>
<p>NumPy, the fundamental package for numerical computing in Python, provides powerful tools for generating arrays with evenly spaced values. In this article, we'll delve into the functions 'range', 'arange', 'linspace', and 'logspace', exploring their functionalities and use cases.</p>

In [1]:
import numpy as np


<h> 1. range

In [4]:
range(10)
range(0,10,2)
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
list(range(0,10,2))  # we can also create a list by using range funciton 


[0, 2, 4, 6, 8]

In [8]:
print(7 in range(10))

True


In [9]:
print(11 in range(10))

False


In [23]:
madhav=list(range(0,10,0.5))  #'float' object cannot be interpreted as an integer this error will show
madhav

TypeError: 'float' object cannot be interpreted as an integer

<h> 2. arrange </h>
<p> like range funciton in list arange has also the functionalities for numpy array and it has also more functionalities than numpy

In [12]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr1=np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [17]:
arr=np.arange(10,0,-2)
arr

array([10,  8,  6,  4,  2])

In [20]:
# funcitonalities of printing floating number that has arange funciton but not have range 
np.arange(10,0,-0.4)

array([10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,  6. ,
        5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ,  1.6,
        1.2,  0.8,  0.4])

<h> 3. linespace </h>
<p> it will create the numbers having same distance among them 

In [31]:
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [32]:
np.linspace(0,11,8)

array([ 0.        ,  1.57142857,  3.14285714,  4.71428571,  6.28571429,
        7.85714286,  9.42857143, 11.        ])

In [33]:
np.linspace(1,12,4)

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])

In [36]:
np.linspace(1,12,4,endpoint=True,retstep=True)

(array([ 1.        ,  4.66666667,  8.33333333, 12.        ]),
 np.float64(3.6666666666666665))

In [37]:
np.linspace(12,0,-0.4,endpoint=True,retstep=True)

TypeError: 'float' object cannot be interpreted as an integer

<h> 4. logarithmic funcitons </h>
<p>  The 'logspace' function in NumPy generates arrays with evenly spaced values on a logarithmic scale.

In [38]:
np.logspace(0 ,10)

array([1.00000000e+00, 1.59985872e+00, 2.55954792e+00, 4.09491506e+00,
       6.55128557e+00, 1.04811313e+01, 1.67683294e+01, 2.68269580e+01,
       4.29193426e+01, 6.86648845e+01, 1.09854114e+02, 1.75751062e+02,
       2.81176870e+02, 4.49843267e+02, 7.19685673e+02, 1.15139540e+03,
       1.84206997e+03, 2.94705170e+03, 4.71486636e+03, 7.54312006e+03,
       1.20679264e+04, 1.93069773e+04, 3.08884360e+04, 4.94171336e+04,
       7.90604321e+04, 1.26485522e+05, 2.02358965e+05, 3.23745754e+05,
       5.17947468e+05, 8.28642773e+05, 1.32571137e+06, 2.12095089e+06,
       3.39322177e+06, 5.42867544e+06, 8.68511374e+06, 1.38949549e+07,
       2.22299648e+07, 3.55648031e+07, 5.68986603e+07, 9.10298178e+07,
       1.45634848e+08, 2.32995181e+08, 3.72759372e+08, 5.96362332e+08,
       9.54095476e+08, 1.52641797e+09, 2.44205309e+09, 3.90693994e+09,
       6.25055193e+09, 1.00000000e+10])

In [40]:
np.logspace(10,0,2)

array([1.e+10, 1.e+00])

In [42]:
np.logspace(1,12,endpoint=2,base=2)

array([2.00000000e+00, 2.33672798e+00, 2.73014882e+00, 3.18980756e+00,
       3.72685628e+00, 4.35432466e+00, 5.08743612e+00, 5.94397716e+00,
       6.94472885e+00, 8.11397110e+00, 9.48007162e+00, 1.10761743e+01,
       1.29410032e+01, 1.51198021e+01, 1.76654322e+01, 2.06396548e+01,
       2.41146294e+01, 2.81746646e+01, 3.29182635e+01, 3.84605136e+01,
       4.49358790e+01, 5.25014628e+01, 6.13408184e+01, 7.16684032e+01,
       8.37347814e+01, 9.78327031e+01, 1.14304207e+02, 1.33548919e+02,
       1.56033748e+02, 1.82304212e+02, 2.12997676e+02, 2.48858814e+02,
       2.90757676e+02, 3.39710798e+02, 3.96905862e+02, 4.63730516e+02,
       5.41806035e+02, 6.33026660e+02, 7.39605552e+02, 8.64128492e+02,
       1.00961661e+03, 1.17959969e+03, 1.37820180e+03, 1.61024135e+03,
       1.88134800e+03, 2.19809925e+03, 2.56818001e+03, 3.00056904e+03,
       3.50575680e+03, 4.09600000e+03])

In [45]:
arr=np.logspace(1,120,3,endpoint=True,base=2)
arr

array([2.00000000e+00, 1.63047723e+18, 1.32922800e+36])