##### =================== Determinant ==================

i

In [1]:
import numpy as np 


In [10]:
arr1=np.array([[1,2],[3,4]])
print(arr1)

print("*"*10)

determinant=np.linalg.det(arr1)
print(determinant)


[[1 2]
 [3 4]]
**********
-2.0000000000000004


In [11]:
arr2=np.array(((1,2,3),(2,5,6),(11,12,13)))
print(arr2)

determinant_2=np.linalg.det(arr2)
determinant_2

[[ 1  2  3]
 [ 2  5  6]
 [11 12 13]]


np.float64(-20.000000000000007)

#### ===================== Transpose of a Matrix ===================


In [13]:
transpose_=np.transpose(arr2)  # by using numpy we can directly solve these kind of Problem 
transpose_

array([[ 1,  2, 11],
       [ 2,  5, 12],
       [ 3,  6, 13]])

In [14]:
arr3=np.array([[1,2,3,4],[2,3,4,5]])
transpose=np.transpose(arr3)
transpose

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

#### ===================== Inverse of Matrix ======================
###### for inverse it is necessary to have the determinant of that matrix should be non zero 

In [15]:
arr2=np.array(((1,2,3),(2,5,6),(11,12,13)))

inverse=np.linalg.inv(arr2)
inverse

array([[ 3.50000000e-01, -5.00000000e-01,  1.50000000e-01],
       [-2.00000000e+00,  1.00000000e+00, -4.92437632e-17],
       [ 1.55000000e+00, -5.00000000e-01, -5.00000000e-02]])