<h>-- NumpyArray    Vs    List -- 

In [3]:
lst=[1,2,3]
print(lst)
print(type(lst))


import numpy as np
arr= np.array([1,2,3])
print(arr)
print(type(arr))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


<h>Comparing the elements of array and list

In [4]:
print(arr==lst)

[ True  True  True]


<h> Function to convert the array into list

In [7]:
lst2=[1,2,3]
arr2=np.array([1,2,4])

print(lst2)
print(arr2)
print(arr2.tolist())  # it will convert the numpy array into list

[1, 2, 3]
[1 2 4]
[1, 2, 4]


In [11]:
lst=[1,2,2]
print(lst)
print(type(lst))


arr= np.array([1,2,3])
print(arr)
print(type(arr))
print(lst==arr)
print(arr.tolist()==lst)

[1, 2, 2]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
[ True  True False]
False


In [12]:
lst=[1,2,3]
print(lst)
print(type(lst))


arr= np.array([1,2,3])
print(arr)
print(type(arr))
print(lst==arr)
print(arr.tolist()==lst)

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
[ True  True  True]
True


<p>--- If the elements of array and list are same but they are not sorted than we can sorted them using ** Sorted function() , in case we want to see them equal

In [16]:
lst=[1,3,2]
print(lst)
print(type(lst))
print('---------')


arr= np.array([1,2,3])
print(arr)
print(type(arr))
print(lst==arr)
print(arr.tolist()==lst)
print('---------')
## In the above statement it will show false because the elements of both array 
## and list are not same 
print('----------')
# so we can sort them using sorted function , but the condition is elements should be same 

print(sorted(lst)==sorted(arr))
print('----------')


[1, 3, 2]
<class 'list'>
---------
[1 2 3]
<class 'numpy.ndarray'>
[ True False False]
False
---------
----------
True
----------


<h>2. Adding the elements in array vs list


In [11]:
lst=[1,3,4,5,6]
print(lst)
print(type(lst))
# adding the elements in lst
lst.append(7)
print(lst)


import numpy as np
arr2=np.array([4,2,3,6,9])
print(arr2)
print(type(arr2))
# adding the element t=in numpy array
arr2= np.append(arr2,45) # important to asign the np.append function into a variable

print(arr2)

[1, 3, 4, 5, 6]
<class 'list'>
[1, 3, 4, 5, 6, 7]
[4 2 3 6 9]
<class 'numpy.ndarray'>
[ 4  2  3  6  9 45]


<h4>3. Removing the elements from the lst vs array

<p>*** At the time of  deletion w ewill give the indexing whilw at the time of adding or append the element will be given 

In [14]:
lst=[1,3,4,5,6]
print(lst)
print(type(lst))
lst.pop() # deletion using pop function 
del lst[-1]  # removing using delete function 

print(lst)

import numpy as np
arr2=np.array([4,2,3,6,9])
print(arr2)
print(type(arr2))

arr2= np.delete(arr2,-2) 


[1, 3, 4, 5, 6]
<class 'list'>
[1, 3, 4]


<h4>4. Updation in array vs list 

<p> *** to update the value there is also need of indexing 

In [18]:
lst2=[2,3.4,5]
print(lst2)
lst[-2]=8
print(lst)


arr3=np.array([2,3,6,9])
print(arr3)
arr3[-4]=0
print(arr3)


[2, 3.4, 5]
[1, 8, 4]
[2 3 6 9]
[0 3 6 9]


<h4> 5. Comarison of time in searching the element in list and  numpy array 

In [49]:
import time 

my_lst=list(range(1000))
# print(my_lst[0:19])

start_time=time.time()

for i in my_lst:
    if 4500 in my_lst:
        print(230)
else:
    print("Number not found")
   
end_time=time.time()

print("searching time for list",end_time-start_time) 

print("--------------")

my_array=np.array(range(1200))
# print(my_array[:120])


start_time=time.time()

for i in range(1200) :
    if 2300 in my_array:
        print("found")
else:
    print("not found")

end_time=time.time()

print("searching time for numpuy array",end_time-start_time)
    

    






Number not found
searching time for list 0.014920949935913086
--------------
not found
searching time for numpuy array 0.009443044662475586


<p> The searching time for numpy arrya is less as compared to list 