<h3>-------------------  Indexing and Slicing In list and numpy array -------------------<h3>

<h6> Indexing and slicing are fundamental operations in array manipulation, allowing users to access and extract specific elements or subarrays from a larger array. In this article, we'll delve into the concepts of indexing and slicing in NumPy arrays, comparing them with similar operations in Python lists.

Indexing and Slicing in Lists:

Indexing and Slicing in Lists:
In Python lists, indexing starts at 0, with negative indices representing elements from the end.
Slicing allows selecting a subset of elements using start, stop, and step parameters.
Examples demonstrate various indexing and slicing operations on a list.</h5>

<h2> Indexing and Slicing in lst 


In [30]:
import numpy as np

In [34]:
lst1=[1,2,3,4,5,6,7]
print(lst1)
print(lst1[3])
print(lst1[2])
print(lst1[0])




[1, 2, 3, 4, 5, 6, 7]
4
3
1


<h4> # Slicing in lst --> when we are doing slicing in lst or array one thing we should keep in our mind
#                    the [:] the number will come out from the given inout index and the last one will be 
#                    the one element before the input index at 


In [36]:
lst1[0:7] # the number in output will be start from 0 index and will end at 6 index 
lst1[0:2]

[1, 2]

In [37]:
lst1[:7]

[1, 2, 3, 4, 5, 6, 7]

In [42]:
lst1[1:]
lst1[0:7:2]
lst1[::-1]

[7, 6, 5, 4, 3, 2, 1]

<h> To reverse the list 

In [46]:
lst1[::-1]
lst1[-1:-7:-1]

[7, 6, 5, 4, 3, 2]

<h> To delete a number from list 


In [47]:
lst1.pop()

7

In [49]:
del lst1[4]

In [51]:
lst1

[1, 2, 3, 4, 6]

<h> To insert the element in lst


In [53]:
lst1.append(30)
lst1

[1, 2, 3, 4, 6, 30, 30]

<h2> Indexing and Slicing with Numpy array </h>



<h5> Indexing and Slicing in Arrays:
Indexing and Slicing in NumPy Arrays:
NumPy arrays support similar indexing and slicing operations as Python lists.
Arrays offer additional functionalities like broadcasting, which allows operations on arrays of different shapes.
Examples showcase indexing and slicing operations on NumPy arrays.

import numpy as np </h6 >

In [55]:
my_arr=np.array([1,2,3,4,5,6,7,8])
print(my_arr)
my_arr[5]

[1 2 3 4 5 6 7 8]


np.int64(6)

In [56]:
print(my_arr[4])

5


In [57]:
my_arr[0:5]

array([1, 2, 3, 4, 5])

<h> Negative Slicing in array


In [59]:
my_arr[-1:-4:-1]

array([8, 7, 6])

<h> Deleting a element from array

In [60]:
np.delete(my_arr,6)

array([1, 2, 3, 4, 5, 6, 8])

<h> Updating the Value in Numpy array

In [64]:
np.insert(my_arr,0,4)

array([4, 1, 2, 3, 4, 5, 6, 7, 8])