In [1]:
import numpy as np

<h4>* Converting the Data Structures into numpy array <h4>
<p> In this section we will look that how we can convert the data structure like tuple, list, dict, set into a numpy aray

<h> (i) converting tuple into array 

In [2]:
tupl=(1,2,34,5)
print(tupl)
print(type(tupl))

arr=np.array(tupl)
print(arr)
print(type(arr))

(1, 2, 34, 5)
<class 'tuple'>
[ 1  2 34  5]
<class 'numpy.ndarray'>


<h> (ii) converting list into array

In [3]:
lst=[1,3,4,5,7]
print(lst)
print(type(lst))

arr1=np.array(lst)
print(arr1)
print(type(arr1))

[1, 3, 4, 5, 7]
<class 'list'>
[1 3 4 5 7]
<class 'numpy.ndarray'>


<h> (iii) converting dictionary  into array 

In [12]:
dct = {1:"madhav",2:"hinani",4:"harsh"}
print(dct)
print("------------")

arr2=np.array(dct)
print(dct)
print(type(dct))
print("------------")

# we can see after the execution that the dictionary is not looking completely like the np array , because it has two parts
# key value pair so we can break them into part and after that we will convert them into list and to list we will convert #
# into aray 

# arr_key=np.array(lst(dicti.keys()))
# print(arr_key)

arr_value=np.array(lst(dct.values()))
print(arr_value)

{1: 'madhav', 2: 'hinani', 4: 'harsh'}
------------
{1: 'madhav', 2: 'hinani', 4: 'harsh'}
<class 'dict'>
------------


TypeError: 'list' object is not callable

<h> (iv) Converting the set into array

In [16]:
set_={1,2,3,4,5}
print(set_)
print(type(set_))

arr3=np.array(set_)
print(arr3)
print(type(arr3))


{1, 2, 3, 4, 5}
<class 'set'>
{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


<h4>** Converting the Datatypes into numpy array

<h>1. converting the integer data types

In [23]:
arr4=np.array([1,2,3,4,5,6])
print(arr4)
print(type(arr4))
print('--------------')

# float
arr_=arr4.astype('float')
print(arr_)
print('--------------')

# string 
arr_=arr4.astype('str')
print(arr_)
print('--------------')
# boolean
arr_=arr4.astype('bool')
print(arr_)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
--------------
[1. 2. 3. 4. 5. 6.]
--------------
['1' '2' '3' '4' '5' '6']
--------------
[ True  True  True  True  True  True]


<h> 2. Converting the float datatypes

In [29]:
arr4=np.array([1.,2.,3.,4.,5.,6.])
print(arr4)
print(type(arr4))
print('--------------')

#int
arr_=arr4.astype('int')
print(arr_)
print('--------------')

#string 
arr_=arr4.astype('str')
print(arr_)

#boolean 
arr_=arr4.astype('bool')
print(arr_)
print(type(arr_))


[1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
--------------
[1 2 3 4 5 6]
--------------
['1.0' '2.0' '3.0' '4.0' '5.0' '6.0']
[ True  True  True  True  True  True]
<class 'numpy.ndarray'>


<h>3. converting the string data type


In [33]:
arr4=np.array(['1','2','3','4','5','6'])
print(arr4)
print(type(arr4))
print('--------------')

# int 
arr_=arr4.astype(int)
print(arr_)

# float
arr_=arr4.astype(float)
print(arr_)

# boolean 
arr_=arr4.astype(bool)
print(arr_)



['1' '2' '3' '4' '5' '6']
<class 'numpy.ndarray'>
--------------
[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[ True  True  True  True  True  True]


In [34]:
arr4=np.array(['1','a','3','4','5','6']) ## this will show error because there should only be a int in the form of string 
                                         ## no other characters can convert in the int 
                                         
print(arr4)
print(type(arr4))
print('--------------')

# int 
arr_=arr4.astype(int)
print(arr_)



['1' 'a' '3' '4' '5' '6']
<class 'numpy.ndarray'>
--------------


ValueError: invalid literal for int() with base 10: np.str_('a')