<h> ------------------------ Creating Fixed Size array -------------------</h>

<p> In data science and numerical computing, creating arrays of fixed sizes and generating random numbers are common tasks. NumPy provides convenient functions for these operations, offering flexibility and efficiency. In this article, we'll explore how to create fixed size arrays filled with zeros, ones, or identity matrices, and how to generate random numbers using NumPy.

In [1]:
import numpy as np


<h> 1. Zeros


In [5]:
arr=np.zeros(3)
arr

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
arr3=np.zeros(((3,4,5)))  # here 3 will be the no of array we want to create and 4 willbe the rows and 5 will be the column

arr3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [13]:
arr4=np.zeros(((5,3,4)),dtype=int)
arr4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [14]:
arr5=np.zeros((3,3),dtype=int)
arr5

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<h> 2. Ones

In [17]:
arr5=np.ones(4,dtype=int)
arr5

array([1, 1, 1, 1])

In [19]:
arr_=np.ones((4,4),dtype=int)
arr_

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
arr6=np.ones(3,4,4) # this will create an error due to multidimensinal concept in array


TypeError: Cannot interpret '4' as a data type

In [22]:
arr6=np.ones(((3,4,4)),dtype=int)
arr6

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [23]:
arr6=np.ones((3,4,4),dtype=int)
arr6

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [24]:
arr6=np.ones(3,4,4,dtype=int)
arr6

TypeError: ones() got multiple values for argument 'dtype'

<h> 3. Eye or Identity matrix

In [26]:
arr7=np.eye() # will throw error if we will not pass the argument 

TypeError: eye() missing 1 required positional argument: 'N'

In [29]:
arr7=np.eye(5)  # by default will create 5*5 identity matrix
arr7 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr7=np.eye(5,5)
arr7


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
arr7=np.eye((3,4,4),dtype=int)

TypeError: 'tuple' object cannot be interpreted as an integer

In [43]:
arr7=np.eye(5,4,dtype=int) # will not show error but create a uneven identity matrix
arr7

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

<h> 4. Random number generator :--

In [53]:
arr1=np.random.uniform(6) # here the value within the paramneter will be the highest value of random 
arr1


5.893573687261716

In [75]:
import numpy as np
print(np.random.randint(low=100, high=200, size=(3, 3)))

[[129 115 141]
 [184 179 150]
 [133 161 101]]


In [76]:
np.random.randint(2,400,40)

array([193, 234, 250,  25, 152, 109, 398, 147, 290, 282,  64, 288, 254,
       364, 117, 125, 152, 393, 268, 210, 331, 208, 364, 284, 268, 195,
       242, 321, 102, 283, 179, 301,  81,  30, 246, 341,   5,  12, 162,
        84], dtype=int32)

In [78]:
np.random.uniform(4,120,(3,3))

array([[ 18.65405614, 116.5597707 ,  31.89646862],
       [ 77.30494467,  35.81573265, 112.16587717],
       [ 70.97900103,  24.70061108,  48.03685041]])