<h> -----  Copy Function -----<h>

<p> In programming, when working with arrays or lists, it's crucial to understand how copying works to avoid unintended side effects. In this article, we'll explore the behavior of the copy function in Python lists and NumPy arrays, highlighting the differences and best practices for copying data structures.

<h> 1. copy function with list 

In [1]:
import numpy as np

In [5]:
lst=[1,2,3,4,5,6]
print(type(lst))

lst2=lst
print(lst)
print(lst2)
print()
print("-"*10)

lst[2]=9
print(lst)  # we can clearly see here if we are updating the value in lst then it is also updating in lst2 
print(lst2)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]

----------
[1, 2, 9, 4, 5, 6]
[1, 2, 9, 4, 5, 6]


<h> To solve this we will use copy() function 

In [11]:
lst=[1,2,3,4,5,6]
print()
lst3=lst.copy()


print(lst)
print(lst3)

print("-"*20)
# Now again updating the value in lst 
lst[1]=8
print(lst)
print(lst3) # so nowe this time it will not update the value in lst3 beacuse we are using copy function 



[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
--------------------
[1, 8, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


<h> 2. Copy Function With Numpy array

In [16]:
arr=np.array((1,2,3,4,5,6))
print(arr)
print()

arr2=arr
print(arr)
print(arr2)

print("-"*20)
#updating the value in arr
arr[2]=9
print(arr)
print(arr2)

[1 2 3 4 5 6]

[1 2 3 4 5 6]
[1 2 3 4 5 6]
--------------------
[1 2 9 4 5 6]
[1 2 9 4 5 6]


<h> so to solve this Problem in numpy array we will also use Copy() function 

In [20]:
arr=np.array([1,2,3,4,5,6])
print(type(arr))

print()
arr3=arr.copy()
arr[2]=80

print(arr)
print(arr3)




<class 'numpy.ndarray'>

[ 1  2 80  4  5  6]
[1 2 3 4 5 6]
